[workspace]
resolver = "2"
members = [
  "crates/lvn",
  "crates/bril",
  "crates/dce",
  "crates/bril-macros",
]

[workspace.dependencies]
eyre = "0.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
